[database]
DB_HOST = "localhost"
DB_NAME = "act-welrent"
DB_USER = "act"
DB_PASS = "H@Z.NU0bNoiT7ayj"

[app]
APP_URL = "https://act.welrent.com"
APP_NAME = "Welrent Act"

[firebase]
; Get these from: Firebase Console → Project Settings → General → Your Apps → Web API Key
FIREBASE_API_KEY    = "AIzaSyD2XOL2dwMH8RLkCeuaUVHGjcZDmGAbveE"
FIREBASE_PROJECT_ID = "welrent"
