<?php
namespace Extensions\Projects\Classes\Renderers;

use App\Abstracts\AbstractModule;
use App\Hooks;
use App\Response;
use App\Route;
use Builders\TitleBuilder;
use Extensions\Projects\Classes\{ProjectJsonStore, ProjectNaming};
use Extensions\Projects\Classes\View\{ViewPageRenderer, ViewSchema};
use Extensions\Projects\Classes\Module\{
    ActionContextRegistry,
    BreadcrumbManager,
    DisplayModeHelper,
    FkChainResolver,
    ModelRecordHelper,
    SelectedMenuSidebarHelper,
    ShowIfEvaluator,
    UrlBuilder
};

!defined('MILK_DIR') && die();

/**
 * Renders the auto-generated view page for a manifest form.
 *
 * If a ViewSchema is available (parsed from view_layout.json), it delegates
 * rendering entirely to ViewPageRenderer. Otherwise, it falls back to the
 * card-based rendering that derives structure from child contexts.
 */
class AutoViewRenderer
{
    protected AbstractModule $module;
    protected AutoListRenderer $listRenderer;
    protected ActionContextRegistry $registry;
    protected FkChainResolver $fkResolver;
    protected BreadcrumbManager $breadcrumbManager;
    protected ShowIfEvaluator $showIfEvaluator;

    /** @var ViewSchema|null Injected by Module when a view_layout.json is present. */
    protected ?ViewSchema $viewSchema = null;

    /** @var ViewPageRenderer|null Lazy-initialized. */
    protected ?ViewPageRenderer $viewPageRenderer = null;

    public function __construct(
        AbstractModule $module,
        AutoListRenderer $listRenderer,
        ActionContextRegistry $registry,
        FkChainResolver $fkResolver,
        BreadcrumbManager $breadcrumbManager,
        ShowIfEvaluator $showIfEvaluator
    ) {
        $this->module = $module;
        $this->listRenderer = $listRenderer;
        $this->registry = $registry;
        $this->fkResolver = $fkResolver;
        $this->breadcrumbManager = $breadcrumbManager;
        $this->showIfEvaluator = $showIfEvaluator;
    }

    /**
     * Inject the parsed view schema. When set, render() delegates to ViewPageRenderer.
     */
    public function setViewSchema(ViewSchema $schema): void
    {
        $this->viewSchema = $schema;
    }

    public function render(): void
    {
        // ------------------------------------------------------------------
        // NEW PATH: JSON-driven view layout
        // ------------------------------------------------------------------
        if ($this->viewSchema !== null) {
            $this->getViewPageRenderer()->render($this->viewSchema);
            return;
        }

        // ------------------------------------------------------------------
        // AUTO-GENERATED PATH: derive structure from child contexts + list renderer
        // ------------------------------------------------------------------
        $this->renderAutoGenerated();
    }

    // ==================================================================
    // New: ViewPageRenderer accessor
    // ==================================================================

    protected function getViewPageRenderer(): ViewPageRenderer
    {
        if ($this->viewPageRenderer === null) {
            $this->viewPageRenderer = new ViewPageRenderer(
                $this->module,
                $this->registry,
                $this->fkResolver,
                $this->breadcrumbManager,
                $this->showIfEvaluator
            );
        }
        return $this->viewPageRenderer;
    }

    // ==================================================================
    // Auto-generated render from contexts
    // ==================================================================

    protected function renderAutoGenerated(): void
    {
        $context = $this->registry->resolveForCurrentRequest();
        if ($context === null) {
            $this->renderError('No form context available for this action.');
            return;
        }
        if (!empty($context['error'])) {
            $this->renderError((string) $context['error']);
            return;
        }

        $viewAction = (string) ($context['view_action'] ?? '');
        if ($viewAction === '') {
            $this->renderError('View action is not enabled for this form.');
            return;
        }

        $modelClass = (string) ($context['model_class'] ?? '');
        if ($modelClass === '' || !class_exists($modelClass)) {
            $this->renderError('Model class not found for this form.');
            return;
        }

        $id = _absint($_REQUEST['id'] ?? 0);
        if ($id <= 0) {
            $this->renderError('Missing record id for view action.');
            return;
        }

        $model = new $modelClass();
        $modelName = (string) ($context['form_name'] ?? 'Model');
        $modelTitle = trim((string) ($context['form_title'] ?? ''));
        if ($modelTitle === '') {
            $modelTitle = ProjectNaming::toTitle($modelName);
        }
        if ($modelTitle === '') {
            $modelTitle = $modelName;
        }
        $modulePage = $this->module->getPage();
        $editAction = (string) ($context['edit_action'] ?? '');
        $viewDisplay = DisplayModeHelper::normalize((string) ($context['view_display'] ?? 'page'));

        $isRoot = (bool) ($context['is_root'] ?? false);
        $fkField = (string) ($context['parent_fk_field'] ?? '');
        $rootField = ProjectNaming::rootIdField();

        $record = $model->getByIdForEdit($id);
        if (!is_object($record) || $record->isEmpty()) {
            $this->renderError("Record #{$id} not found.");
            return;
        }

        $recordParentId = 0;
        $recordRootId = 0;
        $parentId = 0;
        $rootId = 0;

        if (!$isRoot) {
            if ($fkField === '') {
                $this->renderError('Missing parent FK convention for this form.');
                return;
            }

            $rules = $model->getRules();
            if (!isset($rules[$fkField])) {
                $this->renderError("FK field '{$fkField}' is missing in model rules.");
                return;
            }
            if (!isset($rules[$rootField])) {
                $this->renderError("Root field '{$rootField}' is missing in model rules.");
                return;
            }

            $missingFk = $this->fkResolver->findMissingChainField($context);
            if ($missingFk !== null) {
                $this->renderError("Missing parent id. Provide '{$missingFk}' in the URL query string.");
                return;
            }

            $requestedParentId = _absint($_REQUEST[$fkField] ?? 0);
            $requestedRootId = $this->fkResolver->getRootIdFromRequest($context);
            $chainRootError = $this->fkResolver->validateAncestorRootConsistency($context, $requestedRootId);
            if ($chainRootError !== null) {
                $this->renderError($chainRootError);
                return;
            }

            $recordParentId = _absint(ModelRecordHelper::extractFieldValue($record, $fkField));
            $recordRootId = _absint(ModelRecordHelper::extractFieldValue($record, $rootField));

            if ($recordParentId <= 0) {
                $this->renderError("Record #{$id} has empty '{$fkField}'.");
                return;
            }
            if ($requestedParentId > 0 && $requestedParentId !== $recordParentId) {
                $this->renderError("Invalid parent id. URL '{$fkField}={$requestedParentId}' does not match record '{$fkField}={$recordParentId}'.");
                return;
            }
            if ($requestedRootId > 0 && $recordRootId > 0 && $requestedRootId !== $recordRootId) {
                $this->renderError("Invalid root id. URL chain root id '{$requestedRootId}' does not match record '{$rootField}={$recordRootId}'.");
                return;
            }

            $parentId = $requestedParentId > 0 ? $requestedParentId : $recordParentId;
            $rootId = $requestedRootId > 0 ? $requestedRootId : $recordRootId;

            if ($rootId <= 0 && $this->fkResolver->getRootFkField($context) === $fkField) {
                $rootId = $parentId;
            }

            $showIfError = $this->showIfEvaluator->validate($context, $parentId, $rootId);
            if ($showIfError !== null) {
                $this->renderError($showIfError);
                return;
            }
        } else {
            $rootId = $id;
        }

        $chainParams = $this->fkResolver->getChainParams($context);
        $listAction = (string) ($context['list_action'] ?? '');
        $deleteConfirmAction = (string) ($context['delete_confirm_action'] ?? '');
        $editParams = array_merge(['id' => $id], $chainParams);
        $deleteParams = array_merge(['id' => $id], $chainParams);
        $allowEdit = ProjectJsonStore::normalizeBool($context['allow_edit'] ?? true);
        $canDelete = ProjectJsonStore::normalizeBool($context['can_manage_delete_records'] ?? false);

        $formattedData = $record->getFormattedData('array', false);
        if (!is_array($formattedData)) {
            $formattedData = [];
        }

        Hooks::run('projects.record.view.before-render', [
            'hook' => 'projects.record.view.before-render',
            'stage' => 'before_render',
            'page' => $modulePage,
            'context' => $context,
            'request' => $_REQUEST,
            'record_id' => $id,
            'root_id' => $rootId,
            'parent_id' => $parentId,
            'is_root' => $isRoot,
            'model_name' => $modelName,
            'model_title' => $modelTitle,
            'view_display' => $viewDisplay,
            'record' => $record,
            'formatted_data' => $formattedData,
        ]);

        $mainSectionTitle = $modelTitle !== '' ? $modelTitle : 'Detail';

        $detailsEditButtonHtml = $this->buildDetailsEditButtonHtml($editAction, $editParams, $allowEdit);
        $mainDetailsHtml = $this->buildMainDetailsHtml($model, $formattedData, $mainSectionTitle, $detailsEditButtonHtml);
        $childTablesHtml = $this->buildChildTablesHtml($context, $id, $rootId);
        $bodyHtml = $mainDetailsHtml . $childTablesHtml;

        $titleBtns = [];
        if ($listAction !== '') {
            $listUrl = Route::url(UrlBuilder::action($modulePage, $listAction, $chainParams));
            $titleBtns[] = [
                'label' => 'Back to Records',
                'link' => $listUrl,
                'color' => 'secondary',
            ];
        }
        if ($deleteConfirmAction !== '' && $canDelete) {
            $deleteUrl = Route::url(UrlBuilder::action($modulePage, $deleteConfirmAction, $deleteParams));
            $titleBtns[] = [
                'label' => 'Delete Entire Record',
                'link' => $deleteUrl,
                'color' => 'danger',
                'fetch' => 'post',
            ];
        }
        $title = 'Record ID: ' . $id;

        if ($viewDisplay !== 'page' && Response::isJson()) {
            $titleHtml = $this->buildFetchTitleHtml($title, $titleBtns);
            DisplayModeHelper::respond($viewDisplay, $titleHtml, $bodyHtml);
            return;
        }

        $this->breadcrumbManager->apply($context, $modulePage, 'view', $id, $rootId);

        $response = array_merge($this->module->getCommonData(), [
            'title' => $title,
            'title_btns' => $titleBtns,
            'search_html' => '',
            'html' => $bodyHtml,
            'table_id' => 'idView' . preg_replace('/[^a-zA-Z0-9]/', '', $modelName),
        ]);

        SelectedMenuSidebarHelper::applyToResponse($response, $this->module);
        Response::render(MILK_DIR . '/Theme/SharedViews/list_page.php', $response);
    }

    // ==================================================================
    // Auto-generated helpers
    // ==================================================================

    protected function buildMainDetailsHtml(
        object $model,
        array $formattedData,
        string $sectionTitle,
        string $sectionButtonHtml = ''
    ): string {
        $viewRules = $model->getRules('view', true);
        if (empty($viewRules)) {
            $viewRules = $model->getRules();
        }

        $rowsHtml = '';
        foreach ($viewRules as $field => $rule) {
            if ($field === '___action') {
                continue;
            }
            if (!array_key_exists($field, $formattedData)) {
                continue;
            }

            $label = (string) ($rule['label'] ?? $this->toLabel($field));
            $value = $this->formatViewValue($formattedData[$field]);

            $rowsHtml .= '<div class="row py-2 border-bottom">'
                . '<div class="col-lg-4 fw-semibold">' . _r($label) . ':</div>'
                . '<div class="col-lg-8">' . $value . '</div>'
                . '</div>';
        }

        if ($rowsHtml === '') {
            $rowsHtml = '<p class="text-body-secondary mb-0">No view fields configured.</p>';
        }

        $headerHtml = '<div class="d-flex align-items-center justify-content-between gap-2">'
            . '<h5 class="mb-0">' . _r($sectionTitle) . '</h5>';
        if ($sectionButtonHtml !== '') {
            $headerHtml .= '<div>' . $sectionButtonHtml . '</div>';
        }
        $headerHtml .= '</div>';

        return '<div class="card mb-3">'
            . '<div class="card-header">' . $headerHtml . '</div>'
            . '<div class="card-body">' . $rowsHtml . '</div>'
            . '</div>';
    }

    protected function buildDetailsEditButtonHtml(string $editAction, array $editParams, bool $allowEdit): string
    {
        if ($editAction === '' || !$allowEdit) {
            return '';
        }

        $editUrl = UrlBuilder::action($this->module->getPage(), $editAction, $editParams);
        $editDisplay = $this->getDisplayModeForAction($editAction, 'edit');
        $fetchAttr = DisplayModeHelper::buildFetchAttribute($editDisplay);

        return '<a class="btn btn-sm btn-primary" href="' . _r(Route::url($editUrl)) . '"' . $fetchAttr . '>Edit</a>';
    }

    protected function buildFetchTitleHtml(string $title, array $titleBtns): string
    {
        $titleBuilder = TitleBuilder::create($title)->includeMessages(false);
        foreach ($titleBtns as $btn) {
            if (!is_array($btn)) {
                continue;
            }
            $label = (string) ($btn['label'] ?? '');
            if ($label === '') {
                continue;
            }
            $click = (string) ($btn['click'] ?? '');
            if ($click !== '') {
                $titleBuilder->addClickButton(
                    $label,
                    $click,
                    (string) ($btn['color'] ?? 'primary'),
                    (string) ($btn['class'] ?? ''),
                    $this->normalizeBool($btn['small'] ?? false)
                );
                continue;
            }
            $link = (string) ($btn['link'] ?? '');
            if ($link === '') {
                continue;
            }
            $titleBuilder->addButton(
                $label,
                $link,
                (string) ($btn['color'] ?? 'primary'),
                (string) ($btn['class'] ?? ''),
                isset($btn['fetch']) ? (string) $btn['fetch'] : null,
                '',
                $this->normalizeBool($btn['small'] ?? false)
            );
        }

        return $titleBuilder->render();
    }

    protected function buildChildTablesHtml(array $context, int $parentRecordId, int $rootId): string
    {
        $parentFormName = (string) ($context['form_name'] ?? '');
        if ($parentFormName === '') {
            return '';
        }

        $childContexts = $this->registry->getDirectChildContexts($parentFormName);
        if (empty($childContexts)) {
            return '';
        }

        $parentChainParams = $this->fkResolver->getChainParams($context);
        $useSpecialRelatedFormsList = $this->shouldUseSpecialRelatedFormsList($context);
        $relatedFormsListTemplate = $useSpecialRelatedFormsList
            ? MILK_DIR . '/Extensions/Projects/Views/related_forms_special_list.php'
            : MILK_DIR . '/Theme/SharedViews/list_page.php';
        $rowsHtml = '';

        foreach ($childContexts as $childContext) {
            if (!is_array($childContext)) {
                continue;
            }

            $childModelClass = (string) ($childContext['model_class'] ?? '');
            $childFkField = (string) ($childContext['parent_fk_field'] ?? '');
            if ($childModelClass === '' || !class_exists($childModelClass) || $childFkField === '') {
                continue;
            }

            $childModel = new $childModelClass();
            $childRules = $childModel->getRules();
            if (!isset($childRules[$childFkField])) {
                continue;
            }

            $childFormName = (string) ($childContext['form_name'] ?? '');
            $childListAction = (string) ($childContext['list_action'] ?? '');
            $tableId = UrlBuilder::buildViewChildTableId($parentFormName, $childFormName, $parentRecordId);
            $childChainParams = $this->buildChildChainParams(
                $childContext,
                $parentChainParams,
                $childFkField,
                $parentRecordId,
                $rootId
            );

            $listResult = $this->listRenderer->buildListResponse($childContext, [
                'table_id' => $tableId,
                'chain_params' => $childChainParams,
                'parent_id' => $parentRecordId,
                'root_id' => $rootId,
                'request_action' => $childListAction,
                'embedded_view_table' => true,
                'allow_single_record_inline' => true,
                'include_common_data' => false,
                'title_heading_size' => 'h5',
                'skip_ancestor_root_validation' => true,
            ]);

            if (!empty($listResult['error'])) {
                $rowsHtml .= '<div class="row py-2 border-bottom"><div class="col-12">'
                    . '<p class="text-danger mb-0">' . _r((string) $listResult['error']) . '</p>'
                    . '</div></div>';
                continue;
            }

            $childResponse = is_array($listResult['response'] ?? null) ? $listResult['response'] : [];
            $listHtml = DisplayModeHelper::renderViewToString(
                $relatedFormsListTemplate,
                $childResponse
            );

            if ($listHtml === '') {
                continue;
            }

            $rowsHtml .= $listHtml;
        }

        if ($rowsHtml === '') {
            return '';
        }

        return '<div class="card mt-4">'
            . '<div class="card-header"><h5 class="mb-0">Related Forms</h5></div>'
            . '<div class="card-body">' . $rowsHtml . '</div>'
            . '</div>';
    }

    protected function shouldUseSpecialRelatedFormsList(array $context): bool
    {
        return (bool) ($context['is_root'] ?? false) && (string) ($context['view_action'] ?? '') !== '';
    }

    protected function buildChildChainParams(
        array $childContext,
        array $parentChainParams,
        string $childFkField,
        int $parentRecordId,
        int $rootId
    ): array {
        $params = [];
        foreach ($this->fkResolver->getChainFields($childContext) as $chainField) {
            if ($chainField === $childFkField) {
                if ($parentRecordId > 0) {
                    $params[$chainField] = $parentRecordId;
                }
                continue;
            }

            $ancestorId = _absint($parentChainParams[$chainField] ?? 0);
            if ($ancestorId > 0) {
                $params[$chainField] = $ancestorId;
            }
        }

        $rootFkField = $this->fkResolver->getRootFkField($childContext);
        if ($rootId > 0 && $rootFkField !== '' && !isset($params[$rootFkField])) {
            $params[$rootFkField] = $rootId;
        }

        return $params;
    }

    protected function getDisplayModeForAction(string $action, string $type = 'list'): string
    {
        $context = $this->registry->get($action);
        if (!is_array($context)) {
            return 'page';
        }
        return $type === 'edit' ? DisplayModeHelper::getEditMode($context) : DisplayModeHelper::getListMode($context);
    }

    protected function formatViewValue(mixed $value): string
    {
        if ($value === null || $value === '') {
            return '<span class="text-body-secondary">-</span>';
        }
        if (is_bool($value)) {
            return $value ? 'Yes' : 'No';
        }
        if (is_scalar($value)) {
            return _r((string) $value);
        }
        if (is_array($value)) {
            if ($value === []) {
                return '<span class="text-body-secondary">-</span>';
            }
            $values = [];
            array_walk_recursive($value, function ($v) use (&$values) {
                if (is_scalar($v) || $v === null) {
                    $values[] = $v;
                }
            });
            if (!empty($values)) {
                return _r(implode(', ', array_map(static fn($v) => (string) $v, $values)));
            }
            return _r(json_encode($value));
        }
        if (is_object($value)) {
            if (method_exists($value, '__toString')) {
                return _r((string) $value);
            }
            return _r(json_encode($value));
        }
        return _r((string) $value);
    }

    protected function toLabel(string $field): string
    {
        $label = preg_replace(['/([a-z])([A-Z])/', '/_+/', '/[-\s]+/'], ['\\1 \\2', ' ', ' '], $field);
        return ucfirst((string) preg_replace('/\s+/', ' ', trim((string) $label)));
    }

    protected function renderError(string $message): void
    {
        $html = '<div class="container py-4">'
            . '<h1>Projects Extension Error</h1>'
            . '<p class="text-danger">' . _r($message) . '</p>'
            . '</div>';

        Response::themePage('default', $html);
    }

    protected function normalizeBool(mixed $value): bool
    {
        if (is_bool($value)) {
            return $value;
        }
        if (is_int($value)) {
            return $value === 1;
        }
        return in_array(
            strtolower(trim((string) $value)),
            ['1', 'true', 'yes', 'on'],
            true
        );
    }
}
