import { db } from "./db";
import { ensureSchema } from "./ensure-schema";

export type VehicleType = "car" | "motorcycle" | "boat" | "equipment";

export interface CreateContractInput {
  user_uid: string;
  user_email?: string;
  user_name?: string;
  booking_ref?: string;
  vehicle_type?: VehicleType | string;
  vehicle_name: string;
  vehicle_image?: string;
  start_date: string;
  end_date: string;
  days?: number;
  price?: number;
  location?: string;
  status?: string;
  source?: string;
}

const AGREEMENT_BY_TYPE: Record<string, string> = {
  car: "car-rental-agreement",
  motorcycle: "motorcycle-rental-agreement",
  motorbike: "motorcycle-rental-agreement",
  bike: "motorcycle-rental-agreement",
  scooter: "motorcycle-rental-agreement",
  boat: "boat-rental-agreement",
  equipment: "equipment-rental-agreement",
};

function normalizeVehicleType(raw?: string): VehicleType {
  const key = (raw || "car").toLowerCase().trim();
  if (key === "motorcycle" || key === "motorbike" || key === "bike" || key === "scooter") {
    return "motorcycle";
  }
  if (key === "boat") return "boat";
  if (key === "equipment") return "equipment";
  return "car";
}

function makeContractRef(bookingRef?: string): string {
  if (bookingRef && bookingRef.trim()) {
    return `ACT-${bookingRef.trim().toUpperCase()}`;
  }
  return `ACT-${new Date().getFullYear()}-${Math.random().toString(36).slice(2, 8).toUpperCase()}`;
}

function buildContractHtml(input: {
  contract_ref: string;
  booking_ref?: string;
  user_name?: string;
  user_email?: string;
  vehicle_type: string;
  vehicle_name: string;
  start_date: string;
  end_date: string;
  days: number;
  price: number;
  location?: string;
  agreement_slug: string;
}): string {
  return `<article class="legal-document rental-contract">
  <h1>Welrent Rental Contract</h1>
  <p class="legal-meta">
    <strong>Contract:</strong> ${escapeHtml(input.contract_ref)}<br>
    ${input.booking_ref ? `<strong>Booking:</strong> ${escapeHtml(input.booking_ref)}<br>` : ""}
    <strong>Generated by:</strong> Welrent Act<br>
    <em>Created automatically from the Welrent booking platform</em>
  </p>
  <hr>
  <h2>Parties</h2>
  <p><strong>Lessor:</strong> Welrent AutoVerhuur</p>
  <p><strong>Renter:</strong> ${escapeHtml(input.user_name || "Welrent customer")}${
    input.user_email ? ` &lt;${escapeHtml(input.user_email)}&gt;` : ""
  }</p>
  <h2>Vehicle</h2>
  <ul>
    <li><strong>Type:</strong> ${escapeHtml(input.vehicle_type)}</li>
    <li><strong>Vehicle:</strong> ${escapeHtml(input.vehicle_name)}</li>
    <li><strong>Location:</strong> ${escapeHtml(input.location || "As booked")}</li>
  </ul>
  <h2>Rental Period</h2>
  <ul>
    <li><strong>Start:</strong> ${escapeHtml(input.start_date)}</li>
    <li><strong>End:</strong> ${escapeHtml(input.end_date)}</li>
    <li><strong>Days:</strong> ${input.days}</li>
    <li><strong>Price:</strong> €${Number(input.price).toFixed(2)}</li>
  </ul>
  <p>This contract incorporates the standard terms published at
    <a href="/pages/${escapeHtml(input.agreement_slug)}">/pages/${escapeHtml(input.agreement_slug)}</a>.
  </p>
</article>`;
}

function escapeHtml(value: string): string {
  return String(value)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

export async function createContract(input: CreateContractInput) {
  await ensureSchema();

  if (!input.user_uid || !input.vehicle_name || !input.start_date || !input.end_date) {
    throw new Error("Missing required fields: user_uid, vehicle_name, start_date, end_date");
  }

  const vehicle_type = normalizeVehicleType(input.vehicle_type);
  const agreement_slug = AGREEMENT_BY_TYPE[vehicle_type] || AGREEMENT_BY_TYPE.car;
  const days =
    input.days && input.days > 0
      ? input.days
      : Math.max(
          1,
          Math.ceil(
            (new Date(input.end_date).getTime() - new Date(input.start_date).getTime()) /
              (1000 * 60 * 60 * 24)
          )
        );
  const price = Number(input.price ?? 0);
  const contract_ref = makeContractRef(input.booking_ref);
  const status = input.status || "active";
  const source = input.source || "wr-frontend";

  // Idempotent: if booking already has a contract, return it
  if (input.booking_ref) {
    const existing = await db.execute({
      sql: `SELECT * FROM contracts WHERE booking_ref = ? LIMIT 1`,
      args: [input.booking_ref],
    });
    if (existing.rows[0]) {
      return existing.rows[0] as Record<string, unknown>;
    }
  }

  const contract_html = buildContractHtml({
    contract_ref,
    booking_ref: input.booking_ref,
    user_name: input.user_name,
    user_email: input.user_email,
    vehicle_type,
    vehicle_name: input.vehicle_name,
    start_date: input.start_date,
    end_date: input.end_date,
    days,
    price,
    location: input.location,
    agreement_slug,
  });

  await db.execute({
    sql: `INSERT INTO contracts (
      contract_ref, booking_ref, user_uid, user_email, user_name,
      vehicle_type, vehicle_name, vehicle_image, start_date, end_date,
      days, price, location, status, agreement_slug, contract_html, source
    ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)`,
    args: [
      contract_ref,
      input.booking_ref || null,
      input.user_uid,
      input.user_email || null,
      input.user_name || null,
      vehicle_type,
      input.vehicle_name,
      input.vehicle_image || null,
      input.start_date,
      input.end_date,
      days,
      price,
      input.location || null,
      status,
      agreement_slug,
      contract_html,
      source,
    ],
  });

  const created = await db.execute({
    sql: `SELECT * FROM contracts WHERE contract_ref = ? LIMIT 1`,
    args: [contract_ref],
  });

  return created.rows[0] as Record<string, unknown>;
}

export async function listContracts(userUid?: string) {
  await ensureSchema();
  if (userUid) {
    const res = await db.execute({
      sql: `SELECT * FROM contracts WHERE user_uid = ? ORDER BY created_at DESC`,
      args: [userUid],
    });
    return res.rows as Record<string, unknown>[];
  }
  const res = await db.execute(`SELECT * FROM contracts ORDER BY created_at DESC LIMIT 100`);
  return res.rows as Record<string, unknown>[];
}

export async function getContractByRef(ref: string) {
  await ensureSchema();
  const res = await db.execute({
    sql: `SELECT * FROM contracts WHERE contract_ref = ? OR booking_ref = ? LIMIT 1`,
    args: [ref, ref],
  });
  return (res.rows[0] as Record<string, unknown>) || null;
}

export function publicContractUrl(contractRef: string, baseUrl?: string): string {
  const base = (baseUrl || process.env.NEXT_PUBLIC_ACT_URL || "https://act.welrent.com").replace(
    /\/$/,
    ""
  );
  return `${base}/contracts/${encodeURIComponent(contractRef)}`;
}
